### PR TITLE
Make h5serv installable with pip and importable in other Python code

### LINKED ISSUE #102: setup.py and packages on PyPI
Hi !

I think it would really ease the feedback you ask for on https://support.hdfgroup.org/projects/hdfserver/ if this project and its dependencies were easily installable with pip (requirements correctly declared in setup.py, releases pushed to PyPI, ..).

You also mention a version 0.2.0 on https://support.hdfgroup.org/projects/hdfserver/, but there's no corresponding git tag..

I really want to test this, it seems perfect for my use case !
Thanks !

### LINKED ISSUE #122: implicit relative imports cause errors when server package is imported in Python 3 script
I just installed the `server` package from this project and then tried to do `from server import app` in a Python 3 script. This doesn't work, and results in an error:

    ModuleNotFoundError: No module named 'config'

I did some googling, and here's what I came up with: implicit relative imports (eg `import config` in `server/app.py`) aren't valid in Python 3. Confusingly, they still appear to work in certain circumstances (like when you run `python app.py`), but that's down to the details of how `sys.path` is set in that specific case (tldr; they actually function as absolute important statements under these conditions).

### LINKED ISSUE #123: Name of package `server` is too generic
The Python code in this project is all contained in a package named `server`. This means that if I want to important a component of this package in some other piece of Python code I have to write:

    from server import app

This is so generic that if another person reads my code (or myself in a month or two after I've forgotten writing it) they won't have any idea what `server` actually is. The generic name is also likely to conflict with the name of other packages (ie within a user's `site-packages` directory). 

Ideally, the package itself should also be called something like `h5serv`.

### PR DESCRIPTION
**Pull request by telamonian**
Fixes #102, fixes #122, and fixes #123 

Here's my use case for h5serv: I'm writing an HDF5 file viewer plugin for another Python program, and I want to use h5serv as a dependency. Basically, h5serv will be used to handle all of the low-level interactions between the program and a user's HDF5 files. Two things need to happen in order to make this possible:

1. There needs to be a (very) easy way for my end-users to install h5serv (ie `pip install h5serv`)
2. I need to be able to import components of h5serv into my own Python code (ie `from h5serv import app`), and there needs to be a way to use those components to start/stop an HDF5 server without actually having to spawn a new process.

The code in this PR aims to fix all of the things preventing 1. and 2. from happening.

### CODE REVIEW

**Comment by telamonian** [comment]
There's still a bunch of issues to fix that relate to conflicts between how this project's files/paths are structured, and the way in which `setup.py` and Python's `setuptools` "want" those files/paths to be structured.

For example, right now if I try to run the program using the `h5serv` command (the one that's set up by the newly fixed `entry_points` in `setup.py`), I get an error like:

    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/log/h5serv.log'

This is because the `h5serv` command is installed as a script at `/usr/local/h5serv` and h5serv defaults to saving the log file at a position relative to that script.

**Comment by jreadey** [comment]
This makes sense.  When I original setup the project I didn't think it was important to have a setup install script.

 Do you plan to update the PR for the other issues?

  Also the change breaks the travis tests. e.g.: https://travis-ci.org/HDFGroup/h5serv/jobs/437807772. 

  The travis script just needs to use the new name for invoking the server.

**Comment by telamonian** [comment]
>Do you plan to update the PR for the other issues?

Working on it right now!

Aside from the Travis setup, some `import` statements in the tests are also broken by the changes, so I'll fix those too.

There's a bunch of tricky little problems relating to `config` and how it's handled. Here's how I'm thinking to resolve the issues:

- The current default behavior will be preserved when h5serv is invoked via `python app.py`
- When h5serv is invoked via a script or the `h5serv` command, the current working directory will be used as the default data dir, log dir, etc

**Comment by telamonian** [comment]
I took a crack at fixing the remaining issues. At least some tests pass now. The remaining problems all have to do with how the tests... ah... "creatively leverage" the quirks of the Python import system to override `h5serv.config` with their own local `config` module. I know how to fix it, but I'll probably have to make a couple of significant changes to how `config` works (at least internally).

**Comment by jreadey** [comment]
Looks like the Travis tests are passing, that's a good sign.
Are there remaining known problems with the PR?

**Comment by telamonian** [comment]
Just needed some updates to the docs. The PR is now finished. Some notes:

- `setup.py` is totally fixed up, so as soon as you pull the changes and upload them to PyPI people should be able to install using `pip install h5serv`. 
- After installing with `pip`, you can now run h5serv anywhere on a system using the `h5serv` command.
- Two user-visible changes you should be aware of:
    1. h5serv can now be run by `cd`ing to the root dir of the repo and then running `python h5serv`. This was done by fixing up `h5serv/__main__.py`, and replaces `python h5serv/app.py` (which is no longer executable).
        - This was done so that the same set of default paths could be used regardless of how h5serv is invoked.
    2. I got rid of the `log` directory, and by default logs are now saved directly to the working directory.
        - This was done to prevent the `FileNotFoundError` I described above.
        - In the future, you may want to add some more information about the expected file structure (`/data`, `/static`, etc) to the program's startup message, and/or optionally set up missing directories automatically.
- I updated the docs to reflect the above changes.

Let me know if you have any revisions @jreadey, or if the PR looks good to go!

**Comment by jreadey** [comment]
I tried the PR with the h5pyd test suite, and everything worked fine.
Merging into develop.
Thanks for the contribution!

**Pull request merged**
